[phases.setup]
aptPkgs = ["libjemalloc-dev", "libgbm1", "libnss3", "libatk-bridge2.0-0", "libgtk-3-0", "libasound2", "fonts-liberation", "unzip", "tar"]

[phases.install]
cmds = ["npm install -g bun", "PUPPETEER_SKIP_DOWNLOAD=1 bun install"]

[phases.build]
cmds = ["bun x puppeteer browsers install chrome"]

[start]
cmd = "bun start"

[variables]
NODE_VERSION = "22"
PUPPETEER_SKIP_DOWNLOAD = "1"
LD_PRELOAD = "/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"
